Creating a method for CreateParty
shadowlion/transactapi-js pull request #3
Opened 2022-06-10 16:33 UTC by brownrw8

Per documented createParty endpoint: https://api-sandboxdash.norcapsecurities.com/admin_v3/documentation?mid=MTMy

Currently only contains required fields - this can be expanded upon.

Includes minor version bump for minor (non-breaking) dependencies via `npm audit fix`

2022-06-13 14:48 UTC, shadowlion commented on src/createParty/enums.ts
> +  USCITIZEN = "U.S. Citizen",
Change to `US_CITIZEN`

2022-06-13 14:49 UTC, shadowlion commented on src/createParty/enums.ts
> +  USRESIDENT = "U.S. Resident",
Change to `US_RESIDENT`

2022-06-13 14:49 UTC, shadowlion commented on src/createParty/enums.ts
> +  NONRESIDENT = "non-resident",
Change to `NON_RESIDENT`

2022-06-13 14:51 UTC, shadowlion requested changes
Please see comments for changes. Also, can you add a new line to all files as well? I know I didn't add it to `.prettierrc`, but it's gonna change anyways when I open it back on my setup.

2022-06-13 14:51 UTC, shadowlion commented on src/createParty/types.ts
> +  partyId: integer;
Change type to `string` (party ID is normally something like "P12345")

2022-06-13 21:16 UTC, brownrw8 commented
How's it looking now?

2022-06-14 03:48 UTC, shadowlion approved these changes
lgtm - thanks!

2022-06-14 03:48 UTC, merged